name: docs

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install Doxygen 1.9.6
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_6/doxygen-1.9.6.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.6.linux.bin.tar.gz
          ln -s doxygen-1.9.6/bin/doxygen doxygen
      - name: set version
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile
      - name: Generate Documentation
        run: ./doxygen Doxyfile
      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: docs_output/html
          branch: gh-pages